title                    : "Resume"
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
staticman:
  allowedFields          : ['Yaswanth Tavva', 'yaswanth001@e.ntu.edu.sg', 'Research Assistant']

author:
  name             : "Yaswanth Tavva"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Singapore"
  
  
theme: jekyll-theme-cayman
